name: zapac
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.1
  google_maps_flutter: ^2.12.2
  permission_handler: ^12.0.0+1
  http: ^1.2.2
  flutter_polyline_points: ^2.0.0
  web_socket_channel: ^2.4.0
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
