// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYV9_s92K-ojUA5UutDu5e9xRoCi0pX0A',
    appId: '1:714740956555:web:55aba387eee89016c5438e',
    messagingSenderId: '714740956555',
    projectId: 'zapac-5f494',
    authDomain: 'zapac-5f494.firebaseapp.com',
    storageBucket: 'zapac-5f494.firebasestorage.app',
    measurementId: 'G-FXQRXSCTR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChXpMSyZvVW4jFQAcOy6-szVMGvn2wPhA',
    appId: '1:714740956555:android:032da0e3816323c4c5438e',
    messagingSenderId: '714740956555',
    projectId: 'zapac-5f494',
    storageBucket: 'zapac-5f494.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa-wrY69H2wqmw3TBx--fjlbUpb5-oH7c',
    appId: '1:714740956555:ios:4ff1d489b3558129c5438e',
    messagingSenderId: '714740956555',
    projectId: 'zapac-5f494',
    storageBucket: 'zapac-5f494.firebasestorage.app',
    iosBundleId: 'com.example.zapac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa-wrY69H2wqmw3TBx--fjlbUpb5-oH7c',
    appId: '1:714740956555:ios:4ff1d489b3558129c5438e',
    messagingSenderId: '714740956555',
    projectId: 'zapac-5f494',
    storageBucket: 'zapac-5f494.firebasestorage.app',
    iosBundleId: 'com.example.zapac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYV9_s92K-ojUA5UutDu5e9xRoCi0pX0A',
    appId: '1:714740956555:web:164ce7616222d9afc5438e',
    messagingSenderId: '714740956555',
    projectId: 'zapac-5f494',
    authDomain: 'zapac-5f494.firebaseapp.com',
    storageBucket: 'zapac-5f494.firebasestorage.app',
    measurementId: 'G-G9NW5TY90V',
  );
}
