import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Add this import
import 'firebase_options.dart'; // Add this import (generated by flutterfire configure)
import 'auth_screen.dart';
import 'loading_screen.dart'; // Import your new loading screen

void main() async {
  // Make main an async function
  WidgetsFlutterBinding.ensureInitialized(); // Ensure Flutter widgets are initialized
  await Firebase.initializeApp(
    // Initialize Firebase
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MaterialApp(home: AuthScreen(), debugShowCheckedModeBanner: false));
}
